spring:
  application:
    name: UmiVerse-backend
  datasource:
    url: jdbc:mysql://localhost:3306/universe
    username: root
    password: password
  jpa:
    properties:
      hibernate:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat

server:
  port: 8088